version: "3.8"

services:
  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - ACCESS_EXP=3600
      - DB_HOST=mysql
      - DB_NAME=2025DSMHackaton
      - DB_PASSWORD=modooboiroo1766
      - DB_PORT=3306
      - DB_USERNAME=root
      - HEADER=Authorization
      - JPA_FORMAT_SQL=true
      - JPA_HIBERNATE_DDL_AUTO=create
      - JPA_SHOW_SQL=true
      - JWT_SECRET=alasdktkdokqkdtnldkasdadddddddddddddddddddddd
      - LAW_URL=http://apis.data.go.kr/9710000/BillInfoService2/getBillInfoList?serviceKey=s%2Fyzd1uvOR0oi9ffFw1%2FV88CpA9Cf70T6BPyjmL%2Flc%2BzLw%2FuJT3MN0Nf%2F9Lp8I0PNdkhJHzXxBAG50z1pZ0Bjw%3D%3D&pageNo=1&numOfRows=20
      - MAIL_PASSWORD=ivnz diux pzzw nnvg
      - MAIL_USERNAME=mandoo4137@gmail.com
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: 2025DSMHackaton
      MYSQL_ROOT_PASSWORD: modooboiroo1766
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  mysql-data:
